# Generated by Django 5.0.6 on 2024-06-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0003_rename_content_objects_blogpagetags_content_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
