# Generated by Django 5.0.6 on 2024-06-26 15:47

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0004_remove_blogdetail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
